from copy import deepcopy

from app.schemas.store import (
    StoreCollectionRead,
    StoreFiltersRead,
    StoreItemSummary,
    StoreItemType,
    StorePreviewStyle,
    StorePriceRead,
    StoreSortMode,
)

STORE_COLLECTIONS: list[StoreCollectionRead] = [
    StoreCollectionRead(
        id=5101,
        slug="aurora-lab",
        name="Aurora Lab",
        description="Soft light experiments for calm profile styling.",
        accent_color="#77D9FF",
        item_count=5,
        featured=True,
        position=0,
    ),
    StoreCollectionRead(
        id=5102,
        slug="city-pop",
        name="City Pop",
        description="Neon transit, night windows, and glossy commuter color.",
        accent_color="#FF6FB1",
        item_count=5,
        featured=True,
        position=1,
    ),
    StoreCollectionRead(
        id=5103,
        slug="pixel-garden",
        name="Pixel Garden",
        description="Tiny leaves, soft sprites, and playful retro botanicals.",
        accent_color="#74E28B",
        item_count=5,
        featured=False,
        position=2,
    ),
    StoreCollectionRead(
        id=5104,
        slug="quiet-systems",
        name="Quiet Systems",
        description="Minimal interface cosmetics for focused workspace profiles.",
        accent_color="#8EA4FF",
        item_count=4,
        featured=False,
        position=3,
    ),
    StoreCollectionRead(
        id=5105,
        slug="limited-drops",
        name="Limited Drops",
        description="Short-run demo cosmetics with time-boxed availability labels.",
        accent_color="#FFD166",
        item_count=4,
        featured=True,
        starts_at="2026-06-01T00:00:00Z",
        ends_at="2026-06-30T23:59:59Z",
        position=4,
    ),
]


STORE_ITEMS: list[StoreItemSummary] = [
    StoreItemSummary(
        id=6101,
        collection_id=5101,
        type=StoreItemType.AVATAR_DECORATION,
        slug="aurora-ring",
        title="Aurora Ring",
        description="A quiet cyan ring with a soft magenta edge.",
        price=StorePriceRead(price_display="$2.99", orb_price=300),
        tags=["soft", "glow", "frame"],
        colors=["#77D9FF", "#D882FF"],
        theme="aurora",
        preview=StorePreviewStyle(
            accent_color="#77D9FF",
            secondary_color="#D882FF",
            effect="halo",
            icon="sparkles",
        ),
        featured=True,
    ),
    StoreItemSummary(
        id=6102,
        collection_id=5101,
        type=StoreItemType.AVATAR_DECORATION,
        slug="polar-echo",
        title="Polar Echo",
        description="Frosted arcs that sit lightly around the avatar.",
        price=StorePriceRead(price_display="$3.49", nitro_discount_percent=20),
        tags=["ice", "minimal", "frame"],
        colors=["#C9F7FF", "#A7B7FF"],
        theme="aurora",
        preview=StorePreviewStyle(
            accent_color="#C9F7FF",
            secondary_color="#A7B7FF",
            effect="frost",
            icon="snowflake",
        ),
    ),
    StoreItemSummary(
        id=6103,
        collection_id=5102,
        type=StoreItemType.AVATAR_DECORATION,
        slug="metro-glow",
        title="Metro Glow",
        description="A bright commuter-line frame with warm platform lights.",
        price=StorePriceRead(price_display="$3.99", orb_price=420),
        tags=["neon", "city", "frame"],
        colors=["#FF6FB1", "#FFD166"],
        theme="city",
        preview=StorePreviewStyle(
            accent_color="#FF6FB1",
            secondary_color="#FFD166",
            effect="neon",
            icon="train-front",
        ),
        featured=True,
    ),
    StoreItemSummary(
        id=6104,
        collection_id=5103,
        type=StoreItemType.AVATAR_DECORATION,
        slug="sprout-badge",
        title="Sprout Badge",
        description="Small leaf pixels arranged as a profile frame.",
        price=StorePriceRead(price_display="$1.99", orb_price=220),
        tags=["garden", "pixel", "frame"],
        colors=["#74E28B", "#F2E88B"],
        theme="pixel",
        preview=StorePreviewStyle(
            accent_color="#74E28B",
            secondary_color="#F2E88B",
            effect="pixel-leaves",
            icon="sprout",
        ),
    ),
    StoreItemSummary(
        id=6105,
        collection_id=5104,
        type=StoreItemType.AVATAR_DECORATION,
        slug="grid-outline",
        title="Grid Outline",
        description="Thin interface lines that frame the avatar without noise.",
        price=StorePriceRead(price_display="$2.49"),
        tags=["minimal", "system", "frame"],
        colors=["#8EA4FF", "#E9EDF8"],
        theme="systems",
        preview=StorePreviewStyle(
            accent_color="#8EA4FF",
            secondary_color="#E9EDF8",
            effect="grid",
            icon="scan-line",
        ),
    ),
    StoreItemSummary(
        id=6106,
        collection_id=5105,
        type=StoreItemType.AVATAR_DECORATION,
        slug="sunset-ticket",
        title="Sunset Ticket",
        description="A limited warm frame inspired by paper transit tickets.",
        price=StorePriceRead(price_display="$4.49", nitro_discount_percent=15),
        tags=["limited", "sunset", "frame"],
        colors=["#FF9F68", "#FFD166"],
        theme="limited",
        preview=StorePreviewStyle(
            accent_color="#FF9F68",
            secondary_color="#FFD166",
            effect="paper-glow",
            icon="ticket",
        ),
        featured=True,
        limited=True,
    ),
    StoreItemSummary(
        id=6201,
        collection_id=5101,
        type=StoreItemType.PROFILE_EFFECT,
        slug="northern-pulse",
        title="Northern Pulse",
        description="Slow moving light bands for the profile background.",
        price=StorePriceRead(price_display="$4.99", orb_price=520),
        tags=["animated", "glow", "profile"],
        colors=["#77D9FF", "#D882FF"],
        theme="aurora",
        preview=StorePreviewStyle(
            accent_color="#77D9FF",
            secondary_color="#D882FF",
            effect="aurora-wave",
            icon="waves",
        ),
        featured=True,
    ),
    StoreItemSummary(
        id=6202,
        collection_id=5102,
        type=StoreItemType.PROFILE_EFFECT,
        slug="late-train",
        title="Late Train",
        description="Animated light streaks passing behind the profile card.",
        price=StorePriceRead(price_display="$5.49", nitro_discount_percent=20),
        tags=["animated", "city", "profile"],
        colors=["#FF6FB1", "#2DD4BF"],
        theme="city",
        preview=StorePreviewStyle(
            accent_color="#FF6FB1",
            secondary_color="#2DD4BF",
            effect="light-trails",
            icon="route",
        ),
        featured=True,
    ),
    StoreItemSummary(
        id=6203,
        collection_id=5102,
        type=StoreItemType.PROFILE_EFFECT,
        slug="window-rain",
        title="Window Rain",
        description="A calm rainy-window profile effect for night channels.",
        price=StorePriceRead(price_display="$4.49", orb_price=480),
        tags=["animated", "rain", "city"],
        colors=["#6EC6FF", "#192238"],
        theme="city",
        preview=StorePreviewStyle(
            accent_color="#6EC6FF",
            secondary_color="#192238",
            effect="rain",
            icon="cloud-rain",
        ),
    ),
    StoreItemSummary(
        id=6204,
        collection_id=5103,
        type=StoreItemType.PROFILE_EFFECT,
        slug="pixel-bloom",
        title="Pixel Bloom",
        description="Small square petals drifting across the profile preview.",
        price=StorePriceRead(price_display="$3.99", orb_price=400),
        tags=["animated", "garden", "pixel"],
        colors=["#74E28B", "#F7A7D8"],
        theme="pixel",
        preview=StorePreviewStyle(
            accent_color="#74E28B",
            secondary_color="#F7A7D8",
            effect="pixel-petals",
            icon="flower-2",
        ),
    ),
    StoreItemSummary(
        id=6205,
        collection_id=5104,
        type=StoreItemType.PROFILE_EFFECT,
        slug="terminal-breathe",
        title="Terminal Breathe",
        description="Subtle system-panel motion for a focused profile surface.",
        price=StorePriceRead(price_display="$3.49"),
        tags=["animated", "minimal", "system"],
        colors=["#8EA4FF", "#1F2937"],
        theme="systems",
        preview=StorePreviewStyle(
            accent_color="#8EA4FF",
            secondary_color="#1F2937",
            effect="terminal-pulse",
            icon="terminal",
        ),
    ),
    StoreItemSummary(
        id=6206,
        collection_id=5105,
        type=StoreItemType.PROFILE_EFFECT,
        slug="golden-hour-loop",
        title="Golden Hour Loop",
        description="A limited profile background with warm looping shimmer.",
        price=StorePriceRead(price_display="$5.99", orb_price=650),
        tags=["limited", "animated", "warm"],
        colors=["#FFD166", "#FF6B6B"],
        theme="limited",
        preview=StorePreviewStyle(
            accent_color="#FFD166",
            secondary_color="#FF6B6B",
            effect="sun-loop",
            icon="sun",
        ),
        featured=True,
        limited=True,
    ),
    StoreItemSummary(
        id=6301,
        collection_id=5101,
        type=StoreItemType.NAMEPLATE,
        slug="skyline-strip",
        title="Skyline Strip",
        description="A pale blue nameplate with soft horizon bands.",
        price=StorePriceRead(price_display="$1.99", orb_price=180),
        tags=["nameplate", "soft"],
        colors=["#77D9FF", "#FFFFFF"],
        theme="aurora",
        preview=StorePreviewStyle(
            accent_color="#77D9FF",
            secondary_color="#FFFFFF",
            effect="band",
            icon="panel-top",
        ),
    ),
    StoreItemSummary(
        id=6302,
        collection_id=5102,
        type=StoreItemType.NAMEPLATE,
        slug="platform-label",
        title="Platform Label",
        description="A punchy station-sign nameplate with clean contrast.",
        price=StorePriceRead(price_display="$2.49"),
        tags=["nameplate", "city"],
        colors=["#FF6FB1", "#151A2D"],
        theme="city",
        preview=StorePreviewStyle(
            accent_color="#FF6FB1",
            secondary_color="#151A2D",
            effect="label",
            icon="badge",
        ),
    ),
    StoreItemSummary(
        id=6303,
        collection_id=5103,
        type=StoreItemType.NAMEPLATE,
        slug="seedling-plate",
        title="Seedling Plate",
        description="A small garden label with pixel leaf corners.",
        price=StorePriceRead(price_display="$1.49", orb_price=160),
        tags=["nameplate", "garden", "pixel"],
        colors=["#74E28B", "#355E3B"],
        theme="pixel",
        preview=StorePreviewStyle(
            accent_color="#74E28B",
            secondary_color="#355E3B",
            effect="leaf-corners",
            icon="leaf",
        ),
    ),
    StoreItemSummary(
        id=6304,
        collection_id=5104,
        type=StoreItemType.NAMEPLATE,
        slug="command-bar",
        title="Command Bar",
        description="A restrained command-palette nameplate for technical profiles.",
        price=StorePriceRead(price_display="$1.99", nitro_discount_percent=10),
        tags=["nameplate", "minimal", "system"],
        colors=["#8EA4FF", "#111827"],
        theme="systems",
        preview=StorePreviewStyle(
            accent_color="#8EA4FF",
            secondary_color="#111827",
            effect="command-bar",
            icon="command",
        ),
    ),
    StoreItemSummary(
        id=6401,
        collection_id=5101,
        type=StoreItemType.BUNDLE,
        slug="aurora-lab-set",
        title="Aurora Lab Set",
        description="A coordinated frame, profile effect, and nameplate set.",
        price=StorePriceRead(price_display="$7.99", nitro_discount_percent=20),
        tags=["bundle", "glow", "set"],
        colors=["#77D9FF", "#D882FF"],
        theme="aurora",
        preview=StorePreviewStyle(
            accent_color="#77D9FF",
            secondary_color="#D882FF",
            effect="bundle-glow",
            icon="package",
        ),
        featured=True,
        bundle_item_ids=[6101, 6201, 6301],
    ),
    StoreItemSummary(
        id=6402,
        collection_id=5102,
        type=StoreItemType.BUNDLE,
        slug="city-pop-set",
        title="City Pop Set",
        description="Neon commuter cosmetics bundled for a full profile theme.",
        price=StorePriceRead(price_display="$8.49", orb_price=850),
        tags=["bundle", "city", "set"],
        colors=["#FF6FB1", "#FFD166"],
        theme="city",
        preview=StorePreviewStyle(
            accent_color="#FF6FB1",
            secondary_color="#FFD166",
            effect="bundle-neon",
            icon="package-check",
        ),
        bundle_item_ids=[6103, 6202, 6302],
    ),
    StoreItemSummary(
        id=6403,
        collection_id=5103,
        type=StoreItemType.BUNDLE,
        slug="pixel-garden-set",
        title="Pixel Garden Set",
        description="A compact garden bundle with frame, effect, and nameplate.",
        price=StorePriceRead(price_display="$5.99", orb_price=620),
        tags=["bundle", "garden", "pixel"],
        colors=["#74E28B", "#F7A7D8"],
        theme="pixel",
        preview=StorePreviewStyle(
            accent_color="#74E28B",
            secondary_color="#F7A7D8",
            effect="bundle-pixels",
            icon="package-open",
        ),
        bundle_item_ids=[6104, 6204, 6303],
    ),
    StoreItemSummary(
        id=6501,
        collection_id=5103,
        type=StoreItemType.ORB_EXCLUSIVE,
        slug="mint-orb-trail",
        title="Mint Orb Trail",
        description="A Store-only Orb cosmetic with a mint trail preview.",
        price=StorePriceRead(price_display="500 Orbs", orb_price=500),
        tags=["orbs", "exclusive", "garden"],
        colors=["#74E28B", "#CFFFE0"],
        theme="orbs",
        preview=StorePreviewStyle(
            accent_color="#74E28B",
            secondary_color="#CFFFE0",
            effect="orb-trail",
            icon="circle-dot",
        ),
        giftable=False,
    ),
    StoreItemSummary(
        id=6502,
        collection_id=5104,
        type=StoreItemType.ORB_EXCLUSIVE,
        slug="blueprint-orb",
        title="Blueprint Orb",
        description="An Orb-exclusive interface motif for profile previews.",
        price=StorePriceRead(price_display="450 Orbs", orb_price=450),
        tags=["orbs", "exclusive", "system"],
        colors=["#8EA4FF", "#E9EDF8"],
        theme="orbs",
        preview=StorePreviewStyle(
            accent_color="#8EA4FF",
            secondary_color="#E9EDF8",
            effect="blueprint",
            icon="scan",
        ),
        giftable=False,
    ),
    StoreItemSummary(
        id=6503,
        collection_id=5105,
        type=StoreItemType.ORB_EXCLUSIVE,
        slug="sun-coin-flare",
        title="Sun Coin Flare",
        description="A limited Orb-exclusive warm flare cosmetic.",
        price=StorePriceRead(price_display="700 Orbs", orb_price=700),
        tags=["orbs", "exclusive", "limited"],
        colors=["#FFD166", "#FF9F68"],
        theme="orbs",
        preview=StorePreviewStyle(
            accent_color="#FFD166",
            secondary_color="#FF9F68",
            effect="coin-flare",
            icon="coins",
        ),
        featured=True,
        limited=True,
        giftable=False,
    ),
    StoreItemSummary(
        id=6504,
        collection_id=5105,
        type=StoreItemType.ORB_EXCLUSIVE,
        slug="night-market-token",
        title="Night Market Token",
        description="A dark Orb-exclusive token style for late channel sessions.",
        price=StorePriceRead(price_display="620 Orbs", orb_price=620),
        tags=["orbs", "exclusive", "night"],
        colors=["#2DD4BF", "#111827"],
        theme="orbs",
        preview=StorePreviewStyle(
            accent_color="#2DD4BF",
            secondary_color="#111827",
            effect="token-glow",
            icon="badge-cent",
        ),
        limited=True,
        giftable=False,
    ),
]


def list_store_collections() -> list[StoreCollectionRead]:
    return deepcopy(STORE_COLLECTIONS)


def list_store_items() -> list[StoreItemSummary]:
    return deepcopy(STORE_ITEMS)


def get_store_item(item_id: int) -> StoreItemSummary:
    for item in STORE_ITEMS:
        if item.id == item_id:
            return deepcopy(item)
    raise KeyError(item_id)


def build_store_filters() -> StoreFiltersRead:
    return StoreFiltersRead(
        item_types=list(StoreItemType),
        colors=sorted({color for item in STORE_ITEMS for color in item.colors}),
        themes=sorted({item.theme for item in STORE_ITEMS}),
        collections=list_store_collections(),
        sort_modes=list(StoreSortMode),
    )
